FROM centos:latest

MAINTAINER Nicolás de la Torre <ntorre@edrans.com>

RUN rpm -Uvhl http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-2.noarch.rpm && yum update -y && yum upgrade -y && yum clean all -y
