FROM node:10-alpine

RUN npm i -g \
    @babel/cli@7.1.2 @babel/core@7.1.2 @babel/node@7.0.0 \
    @babel/plugin-syntax-object-rest-spread@7.0.0 \
    @babel/plugin-transform-modules-commonjs@7.1.0 \
    @kapmug/babel-plugin-inline-import@3.0.1 \
    nodemon@^1.18.4
