FROM archlinux/base:latest
RUN pacman -Syyu --noconfirm
RUN pacman -S --noconfirm make \
        texlive-core \
	texlive-bibtexextra \
	texlive-fontsextra \
	texlive-formatsextra \
	texlive-games \
	texlive-humanities \
	texlive-latexextra \
	texlive-music \
	texlive-pictures \
	texlive-pstricks \
	texlive-publishers \
	texlive-science

