from rayou/sops@sha256:ddef1a65e92dfe172db0cac5b486d549d44744d17eebb75cd6ae35ea9c1e4659
# ^-- sops 3.4

WORKDIR workdir

COPY decrypt-secrets.sh decrypt-secrets.sh

ENTRYPOINT []

CMD ./decrypt-secrets.sh
