# Copyright (c) 2018 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.
FROM aristanetworks/base:2.3
LABEL maintainer="Fabrice Rabaute fabrice@arista.com"

RUN apk add smartmontools && rm -rf /var/cache/apk/*