FROM php:7.0-alpine

MAINTAINER Jan Alfred Richter "falnyr@gmail.com"

RUN curl -L http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -o php-cs-fixer \
    && chmod a+x php-cs-fixer \
    && mv php-cs-fixer /usr/local/bin/php-cs-fixer