ARG BDB_VERSION="4.8.30.NC"

FROM lepetitbloc/bdb:$BDB_VERSION

ARG USE_UPNP=1
ARG WALLET="omegacoin"
ARG BASE_DIR=".omegacoincore/"
ARG CONFIG_FILE="omegacoin.conf"
ARG PORT=7777
ARG RPC_PORT=7778
ARG REPOSITORY="https://github.com/omegacoinnetwork/omegacoin.git"
ARG REF="tags/0.12.5.1"

ENV USE_UPNP=$USE_UPNP \
    WALLET=$WALLET \
    BASE_DIR=$BASE_DIR \
    CONFIG_FILE=$CONFIG_FILE \
    PORT=$PORT \
    RPC_PORT=$RPC_PORT

EXPOSE $PORT $RPC_PORT

RUN apt-get update -y && apt-get install -y \
    libssl-dev \
    libboost-system-dev \
    libboost-filesystem-dev \
    libboost-chrono-dev \
    libboost-program-options-dev \
    libboost-test-dev \
    libboost-thread-dev \
    libminiupnpc-dev \
    libgmp-dev \
    libevent-dev \
    libzmq3-dev \
    automake \
    pkg-config \
    git \
    bsdmainutils \
&& rm -rf /var/lib/apt/lists/* \
&& useradd -lrUm $WALLET \
&& git clone $REPOSITORY /tmp/$WALLET

WORKDIR /tmp/$WALLET

# build
RUN git fetch --tags \
&&  git checkout $REF \
&&  chmod +x autogen.sh share/genbuild.sh src/leveldb/build_detect_platform \
&&  ./autogen.sh \
&&  ./configure CPPFLAGS="-I/usr/local/db4/include -O2" LDFLAGS="-L/usr/local/db4/lib" \
&&  make \
&&  strip src/${WALLET}d src/${WALLET}-cli src/${WALLET}-tx \
&&  mv src/${WALLET}d /usr/local/bin/ \
&&  mv src/${WALLET}-cli /usr/local/bin/ \
&&  mv src/${WALLET}-tx /usr/local/bin/ \
&&  rm -rf /tmp/$WALLET

USER $WALLET

WORKDIR /home/$WALLET

RUN mkdir -p data $BASE_DIR

COPY wallet/conf/masternode.conf ${BASE_DIR}masternode.conf
COPY wallet/conf/dash.conf $BASE_DIR$CONFIG_FILE
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
