FROM postgres:12.1

RUN apt update && apt install -y \
	build-essential git clang llvm postgresql-server-dev-12

# FROM postgres:12.0-alpine

# RUN apk update && apk upgrade \
# 	&& apk add build-base git clang llvm

