FROM alpine:3.4

MAINTAINER Ricardo Quintana github.com/rqc

# Vulnerabilities sourced from https://github.com/eedevops/alpine-cve-db/blob/master/alpine-linux-package-cve-db.json
RUN apk --update --no-cache add xen==4.6.1-r1

CMD ["sh"]