FROM gone/php:nginx
RUN apt-get update && \
    apt-get -yq install \
        libpspell-dev \
        aspell-en	\
        aspell-am	\
        aspell-ar	\
        aspell-ar-large	\
        aspell-bg	\
        aspell-br	\
        aspell-ca	\
        aspell-cs	\
        aspell-cy	\
        aspell-da	\
        aspell-de	\
        aspell-el	\
        aspell-eo	\
        aspell-eo-cx7	\
        aspell-es	\
        aspell-et	\
        aspell-eu	\
        aspell-fa	\
        aspell-fo	\
        aspell-fr	\
        aspell-ga	\
        aspell-gl-minimos	\
        aspell-he	\
        aspell-hr	\
        aspell-hsb	\
        aspell-hu	\
        aspell-hy	\
        aspell-id	\
        aspell-is	\
        aspell-it	\
        aspell-kk	\
        aspell-ku	\
        aspell-lt	\
        aspell-lv	\
        aspell-nl	\
        aspell-pl	\
        aspell-pt-br	\
        aspell-pt-pt	\
        aspell-ro	\
        aspell-ru	\
        aspell-sk	\
        aspell-sl	\
        aspell-sv	\
        aspell-tl	\
        aspell-uk	\
        aspell-uz	\
        && \
    apt-get clean && \
    rm -r /var/lib/apt/lists/*

