# See http://anandmanisankar.com/posts/docker-container-nginx-node-redis-example/

# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER pgambetta@khemlabs.com

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
