FROM      nginx

RUN       mkdir         /var/log/nginx/demo
RUN       mkdir         /var/log/nginx/recette

ADD       apps/         /usr/share/nginx/html
ADD       router/       /etc/nginx/conf.d
