FROM ubuntu:18.04 

RUN apt-get update 
RUN apt-get -q -y upgrade

RUN apt-get -q -y install procps
RUN apt-get -q -y install aptitude
RUN apt-get -q -y install vim
RUN apt-get -q -y install unzip
RUN apt-get -q -y install sudo
RUN apt-get -q -y install software-properties-common
RUN apt-get -q -y install iputils-ping
RUN apt-get -q -y install wget
RUN apt-get -q -y install tree
RUN apt-get -q -y install less
RUN apt-get -q -y install libxml2-utils
