FROM shyouhei/ruby-and-selenium-and-chrome:base

RUN set -ex \
 && mkdir -p /var/lib/apt/lists/partial \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
     ruby=1:2.2.4+0nkmi1~xenial \
     ruby2.2=2.2.6-0nkmi1~xenial \
     libruby2.2=2.2.6-0nkmi1~xenial \
     ruby2.2-dev=2.2.6-0nkmi1~xenial \
 && apt-get autoremove \
 && apt-get clean \
 && rm -rf /var/cache/apt/archives /var/lib/apt/lists

RUN gem install bundler
