#
# Debian image with build tools for creating a Ceylon APT repository
# It needs the output generated by a ceylon/ceylon-package-deb image to do its work
#
FROM ceylon/base-package-deb

MAINTAINER Tako Schotanus <tako@ceylon-lang.org>

LABEL org.ceylon-lang.dockerfile.description="Debian image for creating a Ceylon APT repository" \
    org.ceylon-lang.dockerfile.vendor="RedHat" \
    org.ceylon-lang.dockerfile.version="1.1"

# Make it possible to use an outside GPG key ring
RUN sudo mkdir /gnupg && \
    sudo chown -R ceylon:ceylon /gnupg && \
    touch /gnupg/.novolume && \
    ln -s /gnupg /home/ceylon/.gnupg
VOLUME /gnupg

ADD build.sh /home/ceylon/build.sh

ENTRYPOINT ["/home/ceylon/build.sh"]
CMD []

