#
# Debian image with build tools for creating a Ceylon DEB package
# It needs the output generated by a ceylon/ceylon-build image to do its work
#
FROM ceylon/base-package-deb

MAINTAINER Tako Schotanus <tako@ceylon-lang.org>

LABEL org.ceylon-lang.dockerfile.description="Debian image with build tools for creating a Ceylon DEB package" \
    org.ceylon-lang.dockerfile.vendor="RedHat" \
    org.ceylon-lang.dockerfile.version="1.1"

ADD build.sh /home/ceylon/build.sh

ENTRYPOINT ["/home/ceylon/build.sh"]
CMD []

