FROM php:7.3.5-apache-stretch

MAINTAINER quyenluu

#update ubuntu && install necessary tools
RUN apt-get update && \
    apt-get install --no-install-recommends --no-install-suggests -y \
            ca-certificates \
            nano \
            git \
            wget \
            curl \
            unzip \
            zip \
            apache2 \
            cron && \
    touch /var/log/cron.log && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y nodejs

#install mysql-server
RUN echo "mysql-server mysql-server/root_password password root" | debconf-set-selections \
    && echo "mysql-server mysql-server/root_password_again password root" | debconf-set-selections \
    && apt-get install -y mysql-server

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY docker-php-entrypoint /usr/local/bin/
RUN chmod 755 /usr/local/bin/docker-php-entrypoint
ENTRYPOINT ["/usr/local/bin/docker-php-entrypoint"] 

##<autogenerated>##
COPY apache2-foreground /usr/local/bin/
RUN chmod 755 /usr/local/bin/apache2-foreground
WORKDIR /var/www/html

COPY auto-start.sh /auto-start.sh
RUN chmod a+x /auto-start.sh

EXPOSE 80 3306

#CMD ["/usr/local/bin/apache2-foreground"]
CMD [ "/auto-start.sh" ]