#
# RedHat image with RPM build tools for creating a Ceylon YUM/DNF repository
# It needs the output generated by a ceylon/ceylon-package-rpm image to do its work
#
FROM ceylon/base-package-rpm

MAINTAINER Tako Schotanus <tako@ceylon-lang.org>

LABEL org.ceylon-lang.dockerfile.description="RedHat image with RPM build tools for creating a Ceylon YUM/DNF repository" \
    org.ceylon-lang.dockerfile.vendor="RedHat" \
    org.ceylon-lang.dockerfile.version="1.0"

RUN echo "%_signature gpg" >> /home/ceylon/.rpmmacros && \
    echo "%_gpg_name Ceylon RPM Archive Signing Key"  >> /home/ceylon/.rpmmacros && \
    sudo mkdir /gnupg && \
    sudo chown -R ceylon:ceylon /gnupg && \
    touch /gnupg/.novolume && \
    ln -s /gnupg /home/ceylon/.gnupg

# Make it possible to use an outside GPG key ring
VOLUME /gnupg

ADD build.sh /home/ceylon/build.sh

ENTRYPOINT ["/home/ceylon/build.sh"]
CMD []

