FROM centos:7.2.1511
RUN yum install -y tcsh epel-release \
    && yum install -y gcc-c++ gcc-gfortran scons cmake make autoconf automake yumex wget bzip2 man-db subversion git file tigervnc tigervnc-server fluxbox xterm
