FROM leodido/texlive:2014

RUN mkdir -p ~/texmf/tex/latex \
  && curl -L https://github.com/Jubobs/xcolor-solarized/archive/master.tar.gz | tar vxz -C ~/texmf/tex/latex \
  && curl -L https://github.com/Jubobs/gitdags/archive/master.tar.gz | tar vxz -C ~/texmf/tex/latex
