# Dockerfile for Haskell development on openSUSE Tumbleweed.

FROM opensuse/tumbleweed
LABEL maintainer="Peter Simons <simons@cryp.to>"

RUN zypper --non-interactive install -y \
      cabal-install                     \
      curl                              \
      ghc
