#
# Copyright (c) 2001-2018 Primeton Technologies, Ltd.
# All rights reserved.
#
# author: ZhongWen Li (mailto:lizw@primeton.com)
#

FROM gitlab/gitlab-ce:9.1.10-ce.0

LABEL maintainer="lizw@primeton.com" \
    provider="Primeton Technologies, Ltd."
