FROM ubuntu:16.04

RUN apt-get update && apt-get -y --allow-remove-essential install wget gettext-base python-pip npm gcc nodejs-legacy git python-setuptools python-cffi curl

RUN npm install serverless -g
