FROM alljoynsville/build-essential:latest

MAINTAINER alljoynsville

RUN git clone https://github.com/raspberrypi/tools
ENV PATH $PATH:/home/builder/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin:
