FROM node:12-slim

RUN apt-get update && apt-get install -y \
      build-essential \
      gifsicle \
      libgl1-mesa-glx \
      libjpeg62-turbo-dev \
      liblcms2-dev \
      libpng-dev \
      libwebp-dev \
      libxi6 \
      optipng \
      pngquant
