# openjdk:8u131-jre-alpine based on alpine:3.4
FROM renanpalmeira/graalvm-alpine

##############################
# install bash
##############################
RUN apk add --no-cache --update bash


WORKDIR /

