FROM python:latest

# install python requirements
RUN pip install --upgrade pip

RUN pip install psycopg2

RUN pip install requests

RUN pip install flask
RUN pip install flask-testing
RUN pip install flask-login
RUN pip install flask-failsafe
RUN pip install flask-migrate
RUN pip install flask-wtf
